version: "3.8"
services:
  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    container_name: eureka
    restart: always
    ports:
      - "8761:8761"
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    restart: always
    depends_on:
      - eureka
    ports:
      - "8080:8080"
