version: "3.8"
services:
  eureka:
    build:
      context: .
      dockerfile: eureka/Dockerfile
    container_name: eureka
    restart: always
    ports:
      - "8761:8761"
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway
    restart: always
    depends_on:
      - eureka
    ports:
      - "8080:8080"
