version: "3.8"
services:
  gateway:
    build: gateway
    container_name: gateway
    restart: always
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
    depends_on:
      - eureka
    ports:
      - "8080:8080"
    networks:
      - eureka-network

  eureka:
    build: eureka
    container_name: eureka
    restart: always
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
    ports:
      - "8761:8761"
    networks:
      - eureka-network

networks:
  eureka-network:
